### PR TITLE
Looks like RavenDB4 is getting set up unnecessarily on a bunch of jobs

### PR DESCRIPTION
**Pull request by DavidBoike**
Just happened to notice this merging RepoSync PRs

### CODE REVIEW

**Review by danielmarbach — APPROVED** [review]

**Comment by danielmarbach** [comment]
Does this need to be force merged?

**Comment by DavidBoike** [comment]
Nope, I was just not very smart and dropped a `:`.

**Comment by danielmarbach** [comment]
Wow, I didn't even notice it in the YAML

**Comment by DavidBoike** [comment]
Some reviewer you are! :trollface:

**Pull request merged**
